(function () {
    "use strict";

    angular
        .module("app")
        .constant("apiUrl", "https://localhost:44359/api/v1/datagen/")
        .constant("authUrl", "https://localhost:44359/");
})();

var Enums = Object.freeze({
    sqlType: Object.freeze({ SqlServer: 0, MySql: 1 }),
    columnType: Object.freeze({ RandomText: 0, FirstName: 1, LastName: 2, FullName: 3, Email: 4, Phone: 5, PassportNumber: 6, PostalCode: 7, Country: 8, Region: 9, City: 10, AddressLine1: 11, AddressLine2: 12, FullAddress: 13, LatitudeLongitude: 14, Int: 15, Number: 16, Money: 17, DateTime: 18, Boolean: 19, Autoinc: 20, Guid: 21 }),
    columnTypeInfo: [{ "value": 0, "stringValue": "RandomText", "displayValue": "Random text", "category": "Text" }, { "value": 1, "stringValue": "FirstName", "displayValue": "First name", "category": "Person" }, { "value": 2, "stringValue": "LastName", "displayValue": "Last name", "category": "Person" }, { "value": 3, "stringValue": "FullName", "displayValue": "Full name", "category": "Person" }, { "value": 4, "stringValue": "Email", "displayValue": "E-Mail", "category": "Person" }, { "value": 5, "stringValue": "Phone", "displayValue": "Phone", "category": "Person" }, { "value": 6, "stringValue": "PassportNumber", "displayValue": "Passport/ID", "category": "Person" }, { "value": 7, "stringValue": "PostalCode", "displayValue": "Postal code", "category": "Address" }, { "value": 8, "stringValue": "Country", "displayValue": "Country", "category": "Address" }, { "value": 9, "stringValue": "Region", "displayValue": "Region", "category": "Address" }, { "value": 10, "stringValue": "City", "displayValue": "City", "category": "Address" }, { "value": 11, "stringValue": "AddressLine1", "displayValue": "AddressLine1", "category": "Address" }, { "value": 12, "stringValue": "AddressLine2", "displayValue": "AddressLine2", "category": "Address" }, { "value": 13, "stringValue": "FullAddress", "displayValue": "Full address", "category": "Address" }, { "value": 14, "stringValue": "LatitudeLongitude", "displayValue": "Latitude/Longitude", "category": "Address" }, { "value": 15, "stringValue": "Int", "displayValue": "Integer", "category": "Numbers" }, { "value": 16, "stringValue": "Number", "displayValue": "Number", "category": "Numbers" }, { "value": 17, "stringValue": "Money", "displayValue": "Money", "category": "Numbers" }, { "value": 18, "stringValue": "DateTime", "displayValue": "Date/Time", "category": "Date/Time" }, { "value": 19, "stringValue": "Boolean", "displayValue": "Boolean", "category": "Boolean" }, { "value": 20, "stringValue": "Autoinc", "displayValue": "Autoincrement", "category": "Identity" }, { "value": 21, "stringValue": "Guid", "displayValue": "GUID", "category": "Identity" }],
    fullNameFormat: Object.freeze({ FirstLast: 0, LastFirst: 1, FirstMLast: 2, LastMFirst: 3, FMLast: 4, LastFM: 5 }),
    fullNameFormatInfo: [{ "value": 0, "stringValue": "FirstLast", "displayValue": "First Last (James Williams)", "category": null }, { "value": 1, "stringValue": "LastFirst", "displayValue": "Last First (Williams James)", "category": null }, { "value": 2, "stringValue": "FirstMLast", "displayValue": "First M. Last (James M. Williams)", "category": null }, { "value": 3, "stringValue": "LastMFirst", "displayValue": "Last M. First (Williams M. James)", "category": null }, { "value": 4, "stringValue": "FMLast", "displayValue": "F.M. Last (J.M. Williams)", "category": null }, { "value": 5, "stringValue": "LastFM", "displayValue": "Last F.M. (Williams J.M.)", "category": null }]
});

/*var sqlTypesEnum = Object.freeze({ SqlServer: 0, MySql: 1 });
var columnTypeEnum = Object.freeze({ RandomText: 0, FirstName: 1, LastName: 2, FullName: 3, Email: 4, Phone: 5, PassportNumber: 6, PostalCode: 7, Country: 8, Region: 9, City: 10, AddressLine1: 11, AddressLine2: 12, FullAddress: 13, LatitudeLongitude: 14, Int: 15, Number: 16, Money: 17, DateTime: 18, Boolean: 19, Autoinc: 20, Guid: 21 });
var columnTypeEnumInfo = [{ "value": 0, "stringValue": "RandomText", "displayValue": "Random text", "category": "Text" }, { "value": 1, "stringValue": "FirstName", "displayValue": "First name", "category": "Person" }, { "value": 2, "stringValue": "LastName", "displayValue": "Last name", "category": "Person" }, { "value": 3, "stringValue": "FullName", "displayValue": "Full name", "category": "Person" }, { "value": 4, "stringValue": "Email", "displayValue": "E-Mail", "category": "Person" }, { "value": 5, "stringValue": "Phone", "displayValue": "Phone", "category": "Person" }, { "value": 6, "stringValue": "PassportNumber", "displayValue": "Passport/ID", "category": "Person" }, { "value": 7, "stringValue": "PostalCode", "displayValue": "Postal code", "category": "Address" }, { "value": 8, "stringValue": "Country", "displayValue": "Country", "category": "Address" }, { "value": 9, "stringValue": "Region", "displayValue": "Region", "category": "Address" }, { "value": 10, "stringValue": "City", "displayValue": "City", "category": "Address" }, { "value": 11, "stringValue": "AddressLine1", "displayValue": "AddressLine1", "category": "Address" }, { "value": 12, "stringValue": "AddressLine2", "displayValue": "AddressLine2", "category": "Address" }, { "value": 13, "stringValue": "FullAddress", "displayValue": "Full address", "category": "Address" }, { "value": 14, "stringValue": "LatitudeLongitude", "displayValue": "Latitude/Longitude", "category": "Address" }, { "value": 15, "stringValue": "Int", "displayValue": "Integer", "category": "Numbers" }, { "value": 16, "stringValue": "Number", "displayValue": "Number", "category": "Numbers" }, { "value": 17, "stringValue": "Money", "displayValue": "Money", "category": "Numbers" }, { "value": 18, "stringValue": "DateTime", "displayValue": "Date/Time", "category": "Date/Time" }, { "value": 19, "stringValue": "Boolean", "displayValue": "Boolean", "category": "Boolean" }, { "value": 20, "stringValue": "Autoinc", "displayValue": "Autoincrement", "category": "Identity" }, { "value": 21, "stringValue": "Guid", "displayValue": "GUID", "category": "Identity" }];
var fullNameFormatEnum = Object.freeze({ FirstLast: 0, LastFirst: 1, FirstMLast: 2, LastMFirst: 3, FMLast: 4, LastFM: 5 });
var fullNameFormatEnumInfo = [{ "value": 0, "stringValue": "FirstLast", "displayValue": "First Last (James Williams)", "category": null }, { "value": 1, "stringValue": "LastFirst", "displayValue": "Last First (Williams James)", "category": null }, { "value": 2, "stringValue": "FirstMLast", "displayValue": "First M. Last (James M. Williams)", "category": null }, { "value": 3, "stringValue": "LastMFirst", "displayValue": "Last M. First (Williams M. James)", "category": null }, { "value": 4, "stringValue": "FMLast", "displayValue": "F.M. Last (J.M. Williams)", "category": null }, { "value": 5, "stringValue": "LastFM", "displayValue": "Last F.M. (Williams J.M.)", "category": null }];
*/